#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

sudo apt-get update
sudo apt-get install -y nginx

#code to redirect a specific endpoint (eg: redirect /redirect_me to https://blog.morechekwas.
