#!/bin/bash
#Bash script to display "Best School" 10 times using a while loop

count=0

while [ $count -lt 10 ]
do
        echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
        ((count++))
done

