#!/bin/bash

#Bash script to display the content of the current directory in list format
#Display only the part of the name after the first dash

curr_fil=$(ls)

for i in $curr_fil; do
	echo "$i" | cut -d '-' -f2
done
